all:
	make -C common	 
	make -C building_block	 
	make -C code_generator

clean:
	make -C common clean
	make -C building_block clean
	make -C code_generator clean

tests:
	make -C common tests
	make -C building_block tests
	make -C code_generator tests
